job_name: "department-ingestion-job"
runner: "DataflowRunner"
gcs_input_path: "gs://gcp-de-batch-data-3/Employee.csv"
bigquery_output_table: "gcp-de-batch-sim-464816:Employee_Details_raw.Employee_raw"
temp_location: "gs://gcp-de-batch-data-3/temp"
staging_location: "gs://gcp-de-batch-data-3/staging"
region: "us-east1"
autoscaling: true
num_workers: 4
machine_type: "n1-standard-2"